# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: estatup.github.io
title: 
email: estatup.consultoria@gmail.com
author: Estatup
description: Consultoria estatística 
 
copyright: 'Copyright &copy; 2016 Estatup. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/estatup
  - title: facebook
    url: 
  - title: envelope
    url:    
  - title: "\f0e0" e-mail
    url:
